### ISSUE TITLE
Can't install from pip

### ISSUE THREAD

**Issue by JOST777** [theochem/procrustes#109]
I am on Python 3.8.0. When I try to install procrustes from pip, I get this error:

```
ERROR: Could not find a version that satisfies the requirement qc-procrustes (from versions: none)
ERROR: No matching distribution found for qc-procrustes
```

Also, I can't clone the repo, since I get permission denied:

```
Cloning into 'procrustes'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by fwmeng88** [comment]
Thank you for your interest in our package! Our package has not released to PyPi or Conda yet, which leads to the error you have.

To make it work, you can try the following commands in your terminal within your virtual environment.
```bash
git clone https://github.com/theochem/procrustes
cd procrustes
pip install .
```

If it still doesn't work, please @ me so that I can get the notification and respond faster.

**Comment by JOST777** [comment]
Thanks! I got it working with the method you mentioned. 

It seems like a really cool package. I am experimenting with using it to do alignment of sets of face images via facial landmarks. I might ask some questions later in a new topic.

**Comment by fwmeng88** [comment]
I am very happy this package is helpful for your research. Thanks.

Please feel free to open another issue if needed. I am going to close this one for now.
