### ISSUE TITLE
Description/keywords of the package

### ISSUE THREAD

**Issue by fwmeng88** [theochem/procrustes#3]
We need to add some descriptions for this package.

**Comment by fwmeng88** [comment]
What we need is a short description for this repository, website and topics separate with spaces) for this package.

For the short description, we can put Paul's input, _**Procrustes problems arise when aligning molecules and other objects when evaluating optimal basis transformations, when determining optimal mappings between sets, and in many other contexts. This package includes options to translate, scale, and zero-pad matrices, so that matrices with different centers/scaling/sizes can be considered.**_

For website, we will just simply use the readthedocs one, [https://procrustes.readthedocs.io/en/latest/](https://procrustes.readthedocs.io/en/latest/).

For the description or keywords, we can use: 

- Procrustes-analysis
- orthogonal-Procrustes
- symmetric-Procrustes
- rotational-Procrustes
- permutation-Procrustes
- softassign 
- quadratic-assignment-problem

Please note that repository topics must start with a lowercase letter or number, consist of 35 characters or less, and can include hyphens. A sample look can be accessed at https://github.com/fwmeng88/procrustes.

What do you think on this? Any suggestion is welcome. Thanks.

@PaulWAyers @FarnazH

**Comment by PaulWAyers** [comment]
For the short description I would use:
Procrustes problems occur when measuring the similarity between two objects, represented by matrices. Since the objects can differ (in order (permutation), scaling (magnification), translation (position), rotation (orientation), stretching (deformation), etc., it is relevant to consider transforms of one object to make it as close as possible to the other, leading to various types of Procrustes problems. This package supports general, orthogonal, rotation, permutation, projection, and symmetric Procrustes problems, including both the normal one-sided approach and (for orthogonal and permutation Procrustes) two-sided approaches, where both the rows and columns are transformed. This package includes options to translate, scale, and zero-pad matrices, so that matrices with different centers/scaling/sizes can be considered. These problems occur, for example, when aligning molecules and other objects when evaluating optimal basis transformations, when determining optimal mappings between sets, and in many other contexts. 

Is this too long?

For keywords, I wouldn't use hyphens unless it is required. I like these keywords, but I'd write:
* Procrustes analysis
* orthogonal Procrustes problem
* symmetric Procrustes problem
* rotational Procrustes problem
* generalized Procrustes problem
* permutation Procrustes problem
* quadratic assignment problem
* softassign method
* molecular alignment
* chemical structure similarity

**Comment by fwmeng88** [comment]
Thank you for the feedback, Paul. 

It may be too long of the description. Or we can just put **This package supports general, orthogonal, rotation, permutation, projection, and symmetric Procrustes problems, including both the normal one-sided approach and (for orthogonal and permutation Procrustes) two-sided approaches, where both the rows and columns are transformed.**  And put the whole paragraph into _README.md_ file.

For the keywords, the hyphens are required by GitHub. These keywords seem good enough.  Thank you for helping!

**Comment by PaulWAyers** [comment]
This seems OK. Let's discuss tomorrow.

**Comment by fwmeng88** [comment]
This is fixed and I am going to close it.
